version: '3'

services:
  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/users.sql:/users.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auth

  apiauth:
    hostname: apiauth
    container_name: apiauth
    build: ./auth
    volumes:
      - ./../auth-rest-python:/usr/src/auth
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=jwt-secret-key-prod
      - DATABASE_URL=mysql://root:root@mysql:3306/auth
    links:
      - mysql

  apiquestions:
    hostname: apiquestions
    container_name: apiquestions
    image: node:carbon
    working_dir: /usr/src/question
    volumes:
      - ./../questions-rest-node:/usr/src/question
    environment:
      - DB_URL=mongodb://root:mongo@mongodb:27017/questions?authSource=admin
    command: ["npm", "run", "docker"]
    links:
      - mongodb
      - apiauth
    
  portainer:
    hostname: portainer
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../front/dist:/var/www/html/portal
      - ./../healthcheck:/var/www/html/healthcheck
      - ./../questions-rest-node/public/doc/:/var/www/html/docs/question/
    ports:
      - "8086:80"
    links:
      - portainer
      - apiquestions
      - apiauth